apiVersion: v1
data: {}
kind: Secret
metadata:
  name: alertmanager-router
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    "global":
      "resolve_timeout": "5m"
    "inhibit_rules":
    - "equal":
      - "alertname"
      "source_match":
        "severity": "critical"
      "target_match_re":
        "severity": "warning|info"
    - "equal":
      - "alertname"
      "source_match":
        "severity": "warning"
      "target_match_re":
        "severity": "info"
    "receivers":
    - "name": "Default"
    - "name": "dev-group-data"
      webhook_configs:
      - url: 'http://alertmanager-webhook-dingtalk:8060/dingtalk/just-for-test/send'
    "route":
      "group_by":
      - "alertname"
      "group_interval": "5m"
      "group_wait": "30s"
      "receiver": "Default"
      "repeat_interval": "12h"
      "routes":
      - "match":
          "route": "dev-group-data"
        "receiver": "dev-group-data"
type: Opaque
