apiVersion: v1
kind: Service
metadata:
  labels:
    alertmanager: router
  name: alertmanager-router
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 9093
    targetPort: web
  selector:
    alertmanager: router
    app: alertmanager
  sessionAffinity: ClientIP
