apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-pushgateway 
  namespace: monitoring
  labels:
    prometheus: alert 
spec:
  endpoints:
  - interval: 60s
    port: http 
  selector:
    matchLabels:
      app: prometheus-pushgateway
