apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: alert
  name: prometheus-alert
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 9090
    targetPort: web
  selector:
    app: prometheus
    prometheus: alert
  sessionAffinity: ClientIP
